module.exports =  {
    battlemount : 
    [
        'T8_MOUNT_MAMMOTH_BATTLE@1',
        'T6_MOUNT_SIEGE_BALLISTA',
        'UNIQUE_MOUNT_BEETLE_GOLD',
        'UNIQUE_MOUNT_BEETLE_SILVER',
        'UNIQUE_MOUNT_BEETLE_CRYSTAL',
        'UNIQUE_MOUNT_ARMORED_EAGLE_GOLD',
        'UNIQUE_MOUNT_ARMORED_EAGLE_CRYSTAL',
        'UNIQUE_MOUNT_ARMORED_EAGLE_SILVER',
        'UNIQUE_MOUNT_TOWER_CHARIOT_GOLD',
        'UNIQUE_MOUNT_TOWER_CHARIOT_SILVER',
        'UNIQUE_MOUNT_TOWER_CHARIOT_CRYSTAL',
        'UNIQUE_MOUNT_RHINO_SEASON_SILVER',
        'UNIQUE_MOUNT_RHINO_SEASON_CRYSTAL',
        'UNIQUE_MOUNT_RHINO_SEASON_GOLD',
        'UNIQUE_MOUNT_BEHEMOTH_SILVER',
        'UNIQUE_MOUNT_BEHEMOTH_GOLD',
        'UNIQUE_MOUNT_BEHEMOTH_CRYSTAL',
        'T7_MOUNT_SWAMPDRAGON_BATTLE',
        'T7_MOUNT_ARMORED_SWAMPDRAGON_BATTLE'
    ]
}    